@startuml

start

:Запомление формы;
:Логирование добавлени формы под пользователем, который добавил;

if (Ответственный назначен?) then (Да)
	:Оповещение ответственного;
else (Нет)
endif

if (Есть ли правила расчета времени реакции?) then (Да)
	:Расчет времени реакции;
else (Нет)
endif

if (Есть ли правила расчета времени решения?) then (Да)
	:Расчет времени решения;
else (Нет)
endif

:Оповещение контактного лица;


stop

@enduml
