@startuml

start

	repeat

		if (Прошло время выполнения задачи?) then (Да)

			if (Есть маршрут заявки по времени?) then (Да)
				:Меняем задачу согласно маршруту;
				:Записываем с лог;
			else (Нет)
			endif

			if (Есть тригер на измнение задачи?) then (Да)
				:Оповещаем;
			else (Нет)
			endif

		else (Нет)
		endif

	repeat while ( )

stop

@enduml
