@startuml

start

	repeat

		if (Прошло время реакции на оповещение?) then (Да)
			:Ищем следющего в цепочке ответственного;
			:Оповещаем ответсвенного;
			:Оповещаем клиента;
		else (Нет)
		endif

	repeat while (Ждем)

stop

@enduml
